apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filecoin-trusted-setup-pvc
  namespace: filecoin-trusted-setup
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
